# Numpy

NumPy is a Linear Algebra Library. Numpy is also incredibly fast, as it has bindings to C libraries. Numpy has many built-in functions and capabilities. 

In [1]:
import numpy as np

### Numpy Arrays

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

arange - Return evenly spaced values within a given interval.

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

linspace - Return evenly spaced numbers over a specified interval.

In [11]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [12]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [13]:
np.eye(4) #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(2)

array([0.94196368, 0.18120624])

In [15]:
ranarr = np.random.randint(0,50,10)
ranarr

array([26, 19,  5,  7, 13, 27, 15, 12, 18, 27])

In [16]:
arr = np.arange(25)
print(arr)
arr.reshape(5,5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
print(arr.max())
print(arr.min())
print(arr.shape)
arr_copy = arr.copy()

24
0
(25,)


### Indexing & Selection

In [19]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
print(arr[8])
print(arr[1:5])
print(arr[0:6])

8
[1 2 3 4]
[0 1 2 3 4 5]


In [21]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [22]:
print(arr_2d[1])
print(arr_2d[1,0])
print(arr_2d[:2,1:])

[20 25 30]
20
[[10 15]
 [25 30]]


In [23]:
print(arr > 4)
print(arr[arr>2])

[False False False False False  True  True  True  True  True  True]
[ 3  4  5  6  7  8  9 10]


In [24]:
print(arr_2d.sum())
print(arr_2d.std())
print(arr_2d.sum(axis=0))

225
12.909944487358056
[60 75 90]


In [25]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
np.add(x, y)

array([[ 6,  8],
       [10, 12]])

In [26]:
np.subtract(x, y)

array([[-4, -4],
       [-4, -4]])

In [27]:
np.multiply(x, y)

array([[ 5, 12],
       [21, 32]])

In [28]:
np.divide(x, y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [29]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

### Logical & Trignometry Operations

In [30]:
np.logical_or(False, True)

True

In [31]:
np.logical_and(True, False)

False

In [32]:
x = np.arange(5)
np.logical_not(x<3)

array([False, False, False,  True,  True])

In [33]:
np.binary_repr(10)

'1010'

In [34]:
np.deg2rad(180)

3.141592653589793

In [35]:
np.rad2deg(np.pi)

180.0

In [36]:
x = np.arange(10).reshape((2, 5))
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
np.median(x)

4.5

In [38]:
np.amax(x)

9

In [39]:
np.amin(x)

0

In [40]:
np.isfinite(1)

True

In [41]:
np.isfinite(np.inf)

False

In [42]:
np.lcm(12, 20)

60

In [43]:
np.gcd(12, 20)

4

In [44]:
np.log10([10,100])

array([1., 2.])

In [45]:
np.log2([10,100])

array([3.32192809, 6.64385619])

In [46]:
np.log([10,100])

array([2.30258509, 4.60517019])

### <div style="text-align: right"> Developed & Curated by Mr. Ronik Dedhia</div>